name: Deploy azure uat
on:
  workflow_run:
    workflows: ["Run tests"]
    branches:
     - main
    tags:
      - '*'
    types:
      - completed

env:
  BUILD_NUMBER: ${{ github.event.workflow_run.run_number }}

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Print github context
        env:
            GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"
  deploy-to-uat:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "Deploy to azure uat image:$BUILD_NUMBER"