name: Deploy azure uat

on:
  release:
    types: [published]

env:
  RELEASE_NAME: ${{ github.event.release.tag_name }}

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Build image image:$RELEASE_NAME"

  tests:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Test 1 image:$RELEASE_NAME"
      - run: echo "Test 2 image:$RELEASE_NAME"
    needs: [build-image]

  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Print github context
        env:
            GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"

  deploy-to-uat:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Deploy to azure uat image:$RELEASE_NAME"
    needs: [tests]