name: first-action
env:
  MYBUILD: "1000"
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - run: echo "OK"
      - run: echo "My run number ${{ github.run_number }}"
