name: Run tests
on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'

#on:
#  pull_request:
#    types: [opened, edited, synchronize, reopened]

env:
  BUILD_NUMBER: ${{ github.run_number }}
  BRANCH_REF: ${{ github.ref }}

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Print github context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"

  build-image:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Build image image:${BRANCH_REF##*/}-$BUILD_NUMBER"

  tests:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Test 1 image:${BRANCH_REF##*/}-$BUILD_NUMBER"
      - run: echo "Test 2 image:${BRANCH_REF##*/}-$BUILD_NUMBER"
    needs: [build-image]
