name: Deploy to yandex and azure dev environment
#on:
#  workflow_run:
#    workflows: ["Run tests"]
#    branches: [main]
#    types:
#      - completed

on:
  push:
    branches:
      - main
    tags-ignore:
      - '*'

env:
  BUILD_NUMBER: ${{ github.run_number }}
  BRANCH_NAME: ${{ github.head_ref }}

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Print github context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"

  build-image:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Build image image:$BRANCH_NAME-$BUILD_NUMBER"

  deploy-ya-dev:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Deploy to dev yandex image:$BRANCH_NAME-$BUILD_NUMBER"
    needs: [build-image]

  deploy-azure-dev:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Deploy to dev azure image:$BRANCH_NAME-$BUILD_NUMBER"
    needs: [build-image]